# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 compose-sonarqube-postgresql-init contributors
# embedded h2, evaluation only
name: sonarqube-h2
services:
  sonarqube:
    image: sonarqube:26.7.0.124771-community
    ports:
      - "9000:9000"
    restart: "on-failure"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
